import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-600 h-16 flex items-center px-4">
          <div className="flex w-full">
            <h1 className="font-bold text-2xl text-white">Task Management</h1>
            <Image src="/menu.svg" alt="menu" width={24} height={24} className="ml-auto"/>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
