import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Tsk_Parent from "./components/tsk/tsk_parent";
import { AuthProvider } from "./components/log/AuthContext";
import { AlertProvider } from "./components/alert/alertContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          <AuthProvider>
            <Header />
            <div className="flex min-h-screen">
              <Tsk_Parent>{children}</Tsk_Parent>
            </div>
          </AuthProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
